language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pip install .
script:
- python binary_tree/tests.py -vv
- python knapsack_problem/tests.py
- python -m unittest unpacking_flatten_lists.tests.main -v
deploy:
  provider: pypi
  user: Niccolum
  password:
    secure: UpcEVcC4jsctXeQIv7zVJdWdP/etK3btNwxFL0DkoJ2FHBeqIXPIecCCXiTXHVAOU7g9TgB70WHmQXzUiR/IIqMYgT3u7QGP42q93KTLOPoUdBZU3v4Tit/SlRbGy21VBLD/ORKPe88e+XLb5wyrL1uC10aEtZFDBmXYgEhg11RdsQOXsN1kdum2HPaerri/jZs+jKETj3hsxe7LL0ju10SePQXprt05siiP5DOUK1ydU+uKr92D6mklZSwGHCHL3ap6EtSZvH4wXA8vhq1dlUG1UFzzi6WTmW9ayF9XkQ9zIG4SMhClgU2qzLmLuMPQRIH7PdIyVB3JO4+tfrLCAO89+qXopWGdBnR8gLoVxYEkb5xKulXGcTECbhlFmYPTy8VS4T2SxZKB9m5/o1JA1Gjf7e+WRfGFivmY42sZIiMpI6k42W5I8vZuE7Cpijlqxs9AjWenIauJeIuT/0EAAPDhinUajKsGa91pQhjgv/iZhDYbmSsPbp+7jbhTt36NXYvGLUk9FeMhg7zpbEO43+EZ7NDvTVe0Bzmqhl+EaDLkrIE1RPEUqYTwsFRYNw183VNUE3KT0CUyWhdaI1r3DbX5z5KAWyEeGTNc6CtuoXBUh3JMnj8wyToHKxTxoB7d65U/75UCYCFROKsvjA/ijBtfft97wvkgoAcfg+pmuxU=
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
