language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pip install .
script:
- python binary_tree/tests.py -vv
- python knapsack_problem/tests.py
- python -m unittest unpacking_flatten_lists.tests.main -v
deploy:
  provider: pypi
  user: Niccolum
  password:
    secure: bqYOgm0e0uv5AiZF4hcPEVuh4+y1+62kvtXboP1ZSwlNWpHjErJBb2pB9LRsTvyoEGC3i9lUdBgZ76LwMw0bNTLtNLWZ4kdcdaYvrawkaiez0tlvBCqCdp09yoDKT0/12JZzd6moRJ6RFBn4yBszFqab+fg/iCs5FUEIoFyE8Drsoo/iPqFfs0T8daIgy40kIP+urEsbWj4QS7+qtBHm/ZzgcxHesMnYu/uWGXP3o6d5sxq1TS+OZsBCMT7Ua7F24Pr43P43h5Wjv+bUWreu1EFSIfLvIruk9q216CVGd0nvFaTDVK3/OJkOEh9QsJtundxkEhY54TtvtvRq4MmFt2N0GKA539wAjm1A05M+ih2Ak3MCOjH4ImoJ1ILp+PNSk0TGPJsyTm3e5Hq0mXZCgc2LmRjQZlR2v37mzrjQHW3WVwNS7Yk7dXyHmQ0wKpbFTlxg1tJ0cb3hlpCUYK143XQS+xblw5SfurikpdcDqP/cmoJW8jlr4JSw4XwC2UQAw1sysE161JGbf/1wwiLI/q+SzQJIUMxBYKZE7ewJT8Bsefx7KrPEc2N1fESitHiY96v0wNSBbgaPwWrkEuxtmEy1RRQevlJpkW/FFbme7KTj0Q3SwSA+2M8OYXh+UvifG1D0ntCiPYA2KlKfAOtrSzkNaonT00/1UDiM4vNJ0/E=
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
