language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pip install .
script:
- python binary_tree/tests.py -vv
- python knapsack_problem/tests.py
- python -m unittest unpacking_flatten_lists.tests.main -v
deploy:
  provider: pypi
  user: Niccolum
  password:
    secure: W9IOdOymvc7fQ3PIJd7gqb27aOWOoxCUPO3NdMhvZxSfYL/oEv1ArpR6OcJ7lxg46oBa7L43lTrFJwy3l2BhbQPGWgqqxZ+MjwofKD1xzbTeYQ0bkH9hBKHF/aAH/aHpCDUXhq3LJJHuYnj2mjwtIdRYcnb7p4mr0WjDYdnlUDJqIjhcWoNbulDqb4ybu4GZHtYHOfBapa8vHRANuuhlWXTLnYsicTpoKZQblc+QNxHmPHldWeUripg1ozW4COC+wTVulkeSCgZ9xRfBlRZpTyhaEwyqn6su99LGOUIoBezpdd1YsH2NG/IK3XLGpEhlOAKoyVbT09QXhyOVylTI56GADSO0KioIFE/WKquUHO0LaNRy4dgzfZ1/jIo4WFkvS19IdBKy6T+41tqrH57tsBT11XY33NJ9nFYxovUkmAOOnWbvOxkucSvcU8M1QcgWtCrmspdSKjvBpYY0OQr8ftP4/QaQoohIHXBjrgrueQr+y6+8oSFT+dNO6MHJyYxpsbh7G8t7e/Xod3HKItJfOgvXm67yhb5rcrTBqSuKr4Rgk1C0jA0sxdOCS3LhqIcpuDou+qQmfnaSFxPVHeCoUOmTfr+kb8HdXjru/ti77MsWmAvxiK0Q8N8zjnz8yKvE5HMYa0xxDwakqN8l/N2V1skGwmXqOBlaO1L1NgrJzVo=
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
