language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pip install .
script:
- python binary_tree/tests.py -vv
- python knapsack_problem/tests.py
- python -m unittest unpacking_flatten_lists.tests.main -v
deploy:
  provider: pypi
  user: Niccolum
  password:
    secure: aqyCvtYwB29C0SdJrBLR/DYFHnnosLZuh2doZd69ikg7s1Mh8dXUhhQRSEy7tONsW0GcUlh2Rq2ItZHyaVOKPeZqBzGIYXxwtzlmE/CQG1G8bLZQA5mOvBcdd4yRxWs+BYihK8tQm5R8wozyhNdpL3H9cTn2za80tnopTNaJXo6NVIsq1v3mqcb2mgBBaWapmJ7gd7S14VGcFQD6nSOfuPuGtfyXW4vL9htXRn/M5k1cddVzQDjxBOhAf7RaNxf6nYfgvIC0zrCzycSegZlKjMHpT5pTcf+HdXlDg5YCWnV9AR5rFojg/2s7I/bM0M3ZFoPUItc4lZFLNqujYwxlP8daupzHjxJMoCG+SpHPcx8OSBFcdJKrMUXBx8k083pLxhXPU75rBEXgejJIwnF/mOajZbo8TJyFvrzSJsTyUgHKdMkCKFcy5t8WMDMXQ/FiHr7SYzkF7C5JEtiK360auKFB1uaipnsCZ4rYYMOB4iu3y50LD/JJ1/8KVLEQrK16kpH7/bk4FiSvlrMQYPZ/2Kj1VPQCM1Kkh+EJG1TRYyGmfjbYsb86TF3aXOpbFxKtdLQVr8Sv3lqaSVmM9Agm5PMWRkySSajDiU71fEByXvDxDPjB3j+rmpxxlk6rkg+f26jrIK2ve7SsparQLzhFJ2P9C1btXRbzzpqgJm2Z2U0=
  on:
    tags: true
  skip_existing: true
