language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pip install .
script:
- python binary_tree/tests.py -vv
- python knapsack_problem/tests.py
- python -m unittest unpacking_flatten_lists.tests.main -v
deploy:
  provider: pypi
  user: Niccolum
  password:
    secure: kLl74o7ZFZaXf551y+2eom3fPASR75U+1tXzdJOzGMQvBwXlKynzFDjFeEhqNET0zQ5j1cv2v4uQnn/4oeYGxKbVcMxStesj/bO9iXv2yYtZal4+JuvJ59OuXH6UneMZzsd/EznNfn1GlUF1wMsTAf0qXvkStXpbdN2xoj6WakQwPrZc+dwSOD0z0xYfTeUPY1dCaIYZdGhMPJ8JZuACSvh0F6REEsJsTUAMCpXTmo2QZ+qi7qUP5QNw3K89JQwMLm8UD4SiraZjTcdSpErmx+SYmrPcQ4dvQ0Kmxpv20ePl5Fl4ICJDgv1QeMAzMP1DsGDDmj1qScwR7DuW9KXLDo+QdNI7OmL3idrayzB3AivmFC7QiHStDyjuvOwDvfu3PPv7v43qKFDpFNwYells/aEDmGKMmnGAdqlagxK46RYFT842ML8lBy9BILQuVEU7Ekr3U5FDeJLp9Mtdl6SFYFC8zhOCLdz/X2KuWUIC7sThz9C5znPRzvH+soLyO1zyqPrpx2EGww9Mwag5r2yCIQCiuhHW9nxH/4DQwcRD6T1Ue8VxAIp/28ppJmP4plJtv8InRJH3hbYIZ5YKNVriQXyplsGf/awQOja6oHIJBzhNFX9zWBJhu5SodyLRo72jLIbdqUYY5jT9cJfXhkKEaQumdsDfcU++r5KXIiQzC5g=
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
