language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pip install .
script:
- python binary_tree/tests.py -vv
- python knapsack_problem/tests.py
- python -m unittest unpacking_flatten_lists.tests.main -v
deploy:
  provider: pypi
  user: Niccolum
  password:
    secure: KyRpd6PXno0vM+9zL+4gpz0KZl7uc8bj8o/s+tW9R/g0j9IACK7lWFyGLpTyUYHRSgUWyxcbsyCIoYki8qbPic4z8KXioGoNKc1g+/vhIRSkfPRQP4M4XfHWUR1g9GuCb3ydu8e6rOO4VutEGFCTXL54D5FTBl4U8eKADDglQwePrBPn2JxwIBZmDZqnNxxBuSO9nmWF7HCR4XBt9q9gCunPy+KpjSBe0h9SuGZTheSkye2zkM+kxINZih3Qv7hQ/DSrxJWM9MVhRNF6sZiLsv+UT9nahLFv4QDboY7CI9k+wTypbtoV6Bst2f/m1YItpmtDmiC1f+HDRff/Yf6pnHPq4tlNVq6OlQwJQ99JH3QYwVZyZgF52zKOCtCxHZa4/KZRMO1hwVwfieDLt9cywG2Ay0sXR4pBlCGTRxbsLz7QJrSSBlL8SGu4EyQTPOh0cacHp/9YFvFAiDwimFrIJdDZgltqEZFp9n2J2kRU8Ebp9gLfuKRUnWWb5L965LYwgm5ScK0W+RuWuUJ6rwIcrzavQmoAI6GJM1+lltjftXgYNrQwREunMFHLxhl8bTRqXyfIa/kZnccHV8ikz7LTXGH7vGHqwn27O38y+9+NrSZCcOau4cc2bju7H80Azsr9ktROraO121cALbwbTDzqmBnDU48r7QizjyHMQ+a3fN0=
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
