language: python
python:
  - '3.6'
  - '3.7'
env:
  - SNYK_TOKEN=d82579d3-a97b-475f-9e7c-9ee561ebd544
install:
  - pip install .
  - pip install coverage codecov
  - npm install -g snyk
script:
  - coverage run binary_tree/tests.py
  - coverage run -a knapsack_problem/tests.py
  - coverage run -a -m unittest unpacking_flatten_lists.tests.main
  - snyk test
after_success:
  - codecov
deploy:
  provider: pypi
  user: Niccolum
  password:
    secure: fyocdZpmgOvLN75dFAD2w8RRXLNnvXhVxc9+LXqUvPdNnc6TDLiwxn3eLf462n3wCbWEtARE7eraGaH5oMGuUCoWiTgk32ad+rM77VJZuIp9Srvq37RV+DLbnfJMLt+yfzcAFYTWlhia2qruS9ZUXjRzp5zuYC1NfZBsoFGofIBZ2aAuapCHsdc1W1xzC8eez7nk5oHOGb2y/lj+d03lSrL2eTCHM2sXRMEu7YD1gsrHM87CwJHPO3XpbFI+wiV0Ku48Z2qgFrrLIODwqDSefDOWdNmkSFhbrGe3mtcV4SGkyO/3OpNqgp9kWr2qxUfkCinfSWOYCN703RQayVP/++bacB3Ope3kSnnbPRQBlOZoZ0TUnEK4kUa48x8RvDo+3U+uT7HbOq8JkyI0RNEW3DAVaEqKdzlA1TUgz0NJ/If59nJTmYDNcxJfLGUp+BvkmA757KaC9P1RdWl1B673nvyHD7KOYugqyXyHI920mPiZFP/PYzHHmjhE2FhS813qfxKOJjcW40t+uZ8/A77LGRapw140nvzHBtXjooVP+cq02qdWQDbeCMZYp1orBR2p+ugWV81qqnsN1UXFUMdcbr68vETGTd8UdnN30CC62XbtRJRFMPWvfyl/ULSiO51bnDzeHJfZBuEM44VQXR63zQUq7zN7hQGB3ykdBQ/cb6s=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
    python: '3.7'
