language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pip install .
script:
- python binary_tree/tests.py -vv
- python knapsack_problem/tests.py
- python -m unittest unpacking_flatten_lists.tests.main -v
deploy:
  provider: pypi
  user: Niccolum
  password:
    secure: m603dK8HP1rmLs/B25b8bbnAbbeEpOXM5FhxmDnBv4+S4zE7dcpANt92Mbz+KUdoR7McrorLl60yBtWSta4jhXoPcbxKaneuDfw55HQ9FWorj3F6xBOd756Ycsti7vUE3fwmtFvZes4tqp5x0/+co2WFmENZYT9Mq6TE5iCX14Lk4trrO7wY7wwoR+2RatafcCV+zLwpDhoxatcSF0zKTHe7mP+aTajMr6FZbYzWWUVkCYTBtUzQNfxKs+GxyQNPMot45BRvIJpu420Lo9sjknl4SXTAxAxAGCt2RgDRJRq0DXKLzy3OIsxwbizzx/XsWzUNThWVDHXVxeAOYxn+LSOC5zc1xfimz2+870pSfa+hHGZ+300jZZPd5r/VtxgNxUXinfiLmirPagH9R6shwiJCIBcRqHXrZImqj7Xs9l0dO4yB9GfMJRlDcjcFXpDwMxGezUoaFT9krRmdoVLqhX6B7ZC1Q/c6UEwEA78o+CWhOEr3yMUhLlJQWYQqrY9Xc2ARz6LrU24049JBd3zuXvAtQNamrUGbd8IUhbvIHxLNEtvQ9qXm8O4+yO7NzfR9+TVJwRQGE1dYLRYiSJPtmk4jLss/Ro8Xx2omY1mOe5kXjtFBg03htKtx2e/f3kwMEeputfe+ZPsjJcf+Xcaf6zb/bjO0U3JMO/yEcKpQYy4=
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
