language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pip install .
script:
- python binary_tree/tests.py -vv
- python knapsack_problem/tests.py
- python -m unittest unpacking_flatten_lists.tests.main -v
deploy:
  provider: pypi
  user: Niccolum
  password:
    secure: n0sUdx8A9zJ7aclz9FOULmhITzvHd8SWXCDvi9YReINvXooFxTdVqSiHBmIrGZKTZuzrVPlxzwE2tlpbdDOL0aUO4JTlc9F7tpyMZCpCR9FCfXQZrJmM8YOXg5FGcsfzl8XeHLORUPNf6elKGXWrJaWYS66Z6GjjW9lTMFWIaD4XYKFHG6Bjc1XNQY5lfsGo1DYHA+VPHWF5aixTQfWpdQuRDD4y3vJpScyYv0q2Hu6amM762O7fnIIkiycaO/bWhukllPQ3NpwnQ21psx2/eRODMso7t5LWBTIva0l0C/lYCr4tXAVTGcahE7eNYeTGTGa/5lesEP9Xm2/flsjpeHK3gKtcRec6C3zzKIV0JKx4c8CNlyKUzYElU4FeXH8cjdvfU9NGJACY7rxUSQZqc8aHBCJp5qp+4nitDWJQmho0IhJRQNPmsO7qlXL3MB9WJUDWfE+Js2MOOevJRetaHhHAcgqtqEL3VOLckRkYb/9po/WnmkGKusvUsPiJ4KyXyURz3ezc992sq0ZEE94wRmYPOy3pEXzCSNCdyjDy549mnysMh4o6s3BpivMllWPBnsmhKk/pOl0R5ERtxY1X1qSYaxgZGsEuZE7SA4hNkXSH+evHC87qIWHGnegoxOkEyeAACOZ6X0/nixlhccOiMDL5b7ijWsl8/rWqEpmow2A=
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
