#!/bin/bash

TAG=$(git describe --tags)

major=0
minor=0
build=0

regex="([0-9]+).([0-9]+).([0-9]+)"
if [[ $TAG =~ $regex ]]; then
    major="${BASH_REMATCH[1]}"
    minor="${BASH_REMATCH[2]}"
    build="${BASH_REMATCH[3]}"
fi

echo -e "Current: \033[33m$major.$minor.$build\033[39m"

if [[ "$1" == "major" ]]; then
    build=0
    minor=0
    major=$(echo $major + 1 | bc)
elif [[ "$1" == "minor" ]]; then
    build=0
    minor=$(echo $minor + 1 | bc)
elif [[ "$1" == "patch" ]]; then
    build=$(echo $build + 1 | bc)
else
    echo "usage: ./verup [major|minor|patch]"
    exit -1
fi

NEW_TAG=$(echo "$major.$minor.$build")
echo -e "New    : \033[32m$NEW_TAG\033[39m"
echo -e "$NEW_TAG" > VERSION

git add .
git commit -m "Version was updated from $TAG to $NEW_TAG"
git tag $NEW_TAG -a -m "$NEW_TAG"
